---
# Execute on all hosts that are part of main group
- hosts: main
  # Root privileges
  become: true
  # Define variable to be used in tasks
  vars:
    doc_root: /var/www/portfolio
  
  # tasks definition section
  tasks:
    - name: Yum update
      yum: update_cache=yes autoremove=yes
      
    - name: Apache install
      yum: name=httpd state=latest
      
    - name: Portfolio document root creation
      file: path={{ doc_root }} state=directory owner=apache group=apache
      
    - name: Setup HTML file
      copy: src=index.html dest={{ doc_root }}/index.html owner=apache group=apache
      
    - name: Setup Apache host file
      template: src=vhost_portfolio.tpl dest=/etc/httpd/conf.d/portfolio.conf
      notify: restart apache
    
    - name: Check if php is installed
      register: php_installed
      command: php -v
      ignore_errors: true
  
    - name: PHP is installed
      debug: var=php_install
      when: php_installed|success
  
    - name: PHP isn't installed
      debug: msg='PHP not available in this VM'
      when: php_installed|failed
  handlers:
    - name: restart apache
      service: name=httpd state=restarted