---
- hosts: webservers
  become: true

  vars:
      database: "nextcloud"
      root_pass: "{{ lookup('env','NEXTCLOUD_DB_PASS_ROOT') }}"
      db_user: "{{ lookup('env','NEXTCLOUD_DB_USER') }}"
      db_pass: "{{ lookup('env','NEXTCLOUD_DB_PASS') }}"
      db_host: "localhost"

  tasks:
      - debug:
          msg: "Nextcloud user :{{ db_user }}"

      - name: MariaDB Install
        apt: name=mariadb-server state=latest

      - name: Install pip
        apt:
            pkg:
                - python3
                - python3-pip
                - python3-setuptools
            update_cache: True
            state: latest

      - name: Install pip virtualenv
        pip: name=virtualenv

      - name: Install the Python MySQLB module
        pip: name=MySQL-python

      - name: Setup root password
        mysql_user:
            name=root
            host="{{ db_host }}"
            password="{{ root_pass }}"
            check_implicit_admin=yes
            login_user="root"
            login_password=""
            state=present

      - name: Create nextcloud database
        mysql_db:
            name: "{{ database }}"
            state: present
        notify: restart-mariadb

      - name: Remove all anonymous users
        mysql_user:
            name: ''
            host: localhost
            state: absent
        notify: restart-mariadb

      - name: Create nextcloud user
        mysql_user:
            host: "{{ db_host }}"
            name: "{{ db_user }}"
            password: "{{ db_pass }}"
            priv: '{{ database }}.*:ALL'
            update_password: always
            state: present
        notify: restart-mariadb

  handlers:
      - name: restart-mariadb
        service: name=mariadb state=restarted
